name: Build

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'
      - 'RELEASING.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'
      - 'RELEASING.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: "Build with ${{ matrix.version }}"
    strategy:
      matrix:
        version: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/dev' }}
        name: Build & Deploy SNAPSHOT
        run: ./mvnw -ntp deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}