name: Build

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'
      - 'RELEASING.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'
      - 'RELEASING.md'

permissions:
  contents: read

jobs:
  build:
    name: "Build with ${{ matrix.version }}"
    strategy:
      matrix:
        version: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          server-password: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build with Maven
        run: ./mvnw -ntp verify


      - if: ${{ github.ref == 'refs/heads/dev' }}
        name: Publish SNAPSHOT package
        env:
          #JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          #JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
          #JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          #JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          #JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          #JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          #JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          #JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -ntp deploy